	<h1><?php echo $header; ?></h1>

	<div id="body">
		<p>The page you are looking at should hold the index page.</p>

		<p>If you would like to edit this page you'll find it located at:</p>
		<code>application/views/welcome_message.php</code>

		<p>The corresponding controller for this page is found at:</p>
		<code>application/controllers/welcome.php</code>

		<p>It is powered by <a href='http://codeigniter.com'>Codeigniter</a> and this is dynamically generated by the framework.</p>
	</div>
